//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_PATENT_LAWSTATE
    {
        public string ID { get; set; }
        public string APP_NUMBER { get; set; }
        public Nullable<System.DateTime> PUB_DATE { get; set; }
        public string LAW_STATE { get; set; }
        public string LAW_STATE_INFORMATION { get; set; }
    }
}
