//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_BOOK
    {
        public string ID { get; set; }
        public Nullable<short> MG_ID { get; set; }
        public string MG_NUM { get; set; }
        public string MG_BOOKNAME { get; set; }
        public string MG_AUTHOR { get; set; }
        public string MG_PUBLISHER { get; set; }
        public Nullable<short> MG_YEAR { get; set; }
        public Nullable<short> MG_PAGENUM { get; set; }
        public string MG_FORMAT { get; set; }
        public string MG_SIZE { get; set; }
    }
}
