//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_PATENT_FAMILY
    {
        public string ID { get; set; }
        public string PATENTFAMILYID { get; set; }
        public string MEMBERPATENT { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
    }
}
